### PR TITLE
Fix gdb build with gcc 4.5.0

### PR DESCRIPTION
**Pull request by VVIsaev**
This patch fixes following error with old gcc compiler:
```
13:06:09  [EXTRA]    Building cross gdb
13:07:18  [ERROR]    /SCRATCH/arcjenkins2/slaves/us01-custom-arcgnu2/workspace/arcoss_verification/sandbox_sg/ARC-GNU-toolchain-verification/build_toolchain-3/crosstool-ng/.build/arc64-snps-linux-gnu/src/gdb/gdb/linespec.c:4276:52: error: could not convert '{minsym, objfile}' from '<brace-enclosed initializer list>' to 'bound_minimal_symbol'
13:07:18  [ERROR]    make[3]: *** [Makefile:1660: linespec.o] Error 1
13:07:18  [ERROR]    make[3]: *** Waiting for unfinished jobs....
13:07:20  [ERROR]    make[2]: *** [Makefile:11723: all-gdb] Error 2
13:07:20  [ERROR]    make[1]: *** [Makefile:1000: all] Error 2
```

### CODE REVIEW

**Review by shahab-vahedi — COMMENTED** [review]
Vladimir, thank you for adding this change targeted for gcc 4.5.0. Looking at the nature of the changes, my immediate response was that this does not seem to be upstreamable, therefore I wanted to reject it. However, I have 3 suggestions:

1) I have no problem per se in merging this change to `arc-2022.03` release. On the other hand, the next release will suffer the same until the same remedy is applied. Please see point 2 regarding that.

2) Maybe it would be more feasible to add this patch to `cross-ng`.

3) Directly upstream these changes. The likelihood of this happening is very slim.

**Comment by VVIsaev** [comment]
HI @shahab-vahedi ,

This is cherry-pick of commit f6b3ad544063314a1e7fcaa703b5e29f5ff10780 from upstream.
